### ISSUE TITLE
How do you ref other models?

### ISSUE THREAD

**Issue by Spazer9** [juampi92/adonis-mongoose-model#25]
I'm trying to use virtuals but i'm getting an error:

`"Cannot overwrite `User` model once compiled."`

My model is like:

```
const BaseModel = use('MongooseModel')

require('./user')
require('./account')

class Membership extends BaseModel {

  static boot ({ schema }) {
    schema.virtual('user', {
      ref: 'User',
      localField: 'user_id',
      foreignField: '_id',
      justOne: true
    })

    schema.virtual('account', {
      ref: 'Account',
      localField: 'account_id',
      foreignField: '_id',
      justOne: true
    })

    this.addHook('preFind', async function(next){
      this.populate('user')
      this.populate('account')
      next()
    })
  }

  static get schemaOptions() {
    return {
      toObject: { virtuals: true },
      toJSON: { virtuals: true }
    }
  }

}

module.exports = Membership.buildModel('Membership')
```

I looked into some solutions online [like this](https://stackoverflow.com/questions/19051041/cannot-overwrite-model-once-compiled-mongoose) and but i'm not sure how I can do that with this adonis integration of mongoose.

**Comment by juampi92** [comment]
Idk why it's saying about overriding the User model, cause it's not involved on that file it seems.

Try to debug it by logging each step, so you'll now if something is trying to redefine the User.
Maybe the problem is not with this file? 

Also you could use schemaOptions to define the toObject and to JSON

````js
static get schemaOptions() {
  return {
    toObject: { virtuals: true },
    toJSON, { virtuals: true }
  }
}
````

**Comment by Spazer9** [comment]
@juampi92 Sorry I left the last line which builds the model (that exists at the end of each model)

**Comment by Spazer9** [comment]
I seem to have fixed it by changing the last line on the required models to:

`module.exports = require('mongoose').models.Account || Account.buildModel('Account')`

and 

`module.exports = require('mongoose').models.User || Account.buildModel('User')`

**Comment by juampi92** [comment]
Mmm but that does not make sense. It seems that you have to check if mongoose has already defined.
You shouldn't.

If it throws an error is because the model is being defined somewhere else, and you need to know that.
You shouldn't build a model without doing Account.buildModel('Account').

Check for a duplicated definition of buildModel('User')
